### ISSUE TITLE
LoginActivity에 ProgressBar 추가 요망

### ISSUE THREAD

**Issue by KRMKGOLD** [thikira/ThikiraAndroid#56]
LoginActiivty에 로그인 버튼을 누르고 딜레이가 있습니다. 이 부분에 ProgressBar를 추가해서 딜레이중이라는 것을 알려줬으면 좋겠습니다.
@choi-seung-min

**Comment by choi-seung-min** [comment]
현재 딜레이가 확인되지 않으나 추후 테스트시에도 같은 문제상황발생시 처리하도록 하겠습니다.

**Comment by KRMKGOLD** [comment]
아 딜레이 심해요

**Comment by choi-seung-min** [comment]
Progress Bar가 추가되었습니다.
