### ISSUE TITLE
MainActivity Event Banner & restaurant item issues

### ISSUE THREAD

**Issue by choi-seung-min** [thikira/ThikiraAndroid#59]
메인액티비티의 이벤트 배너의 인덱싱과 업체 아이템에 있는 업체명이 제대로 출력되지 않습니다.

**Comment by KRMKGOLD** [comment]
THIK-47 branch를 통해서 오류를 수정했습니다. 본 목적인 Infinite & auto scroll 기능을 구현한 후에 PR 승인이 되면 Close합니다.
